# SEO content

title : Smarty Paints! - The Watercolor App
tagline: Real watercolor paints, simplified - track what you own, find close-enough dupes, and finally remember which blue is *that* blue  
description: Browse 3000+ paints, find dupes across brands, create drag-and-drop palettes, and never buy the same paint twice. Palette Keeper is now Smarty Paints!
url: https://smartypaints.app
logo: assets/appicon.png
facebook:
  username: 61555513576494


# Page content

#page title
page_title                                : Smarty Paints!                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6472111419                             # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/ca/app/palette-keeper/id6472111419                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.palettekeeper.palettekeeper                                          # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Smarty Paints!                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Real watercolor paints, simplified. <br><br> Browse 3000+ paints, find dupes across brands, create drag-and-drop palettes, and never buy the same paint twice.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : Neural Appworks LLC                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : contact@neuralappworks.com
facebook_username                         : 61555513576494                                          
instagram_username                        : palette_keeper
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : I love this app!! It's so fun to keep track of everything!! 🤩
    description                           : Michelle S.
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

  - title                                 : I used the app this morning to see if I had a color that matched the one used in the tutorial I was watching. Thankfully I had one that was almost perfect. So it's a very handy app. 😊 
    description                           : Barbara H.
    fontawesome_icon_name                 : 

  - title                                 : I've been looking for an app like this for years. Finally something I can really use to track the pigments I use for each painting. I love it!
    description                           : Tim G. 
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

  - title                                 : I’ve been struggling to organize and keep quick records of my new paints, in addition to creating a good balanced palette. Trying to do this analog takes SOooo much time. Your app is a big help.
    description                           : Skyler J.
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

  - title                                 : oh wow ... I'm really impressed. I always struggle in workshops when they use another brand than me to find the matching color in my brand. THANK YOU 😘🥰😘
    description                           : Iris S.
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

  - title                                 : I haven’t found anything anywhere near as good as your app ... the ‘dupe’ function you’ve now added is just brilliant.
    description                           : Narelle
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header.png                 # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.2

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap